import type { AnalysisResult, Finding } from "./types.js";

export function renderMarkdown(result: AnalysisResult): string {
  const lines: string[] = [
    "# Agent Learning Report",
    "",
    `Score: **${result.score}/100**`,
    "",
    result.summary,
    "",
    `Generated: ${result.generatedAt}`,
    "",
    "## Findings",
    ""
  ];

  if (result.findings.length === 0) {
    lines.push("No findings.");
  } else {
    result.findings.forEach((finding, index) => {
      lines.push(renderFinding(finding, index + 1));
    });
  }

  lines.push("", "## Suggested AGENTS.md Rules", "");
  result.recommendations.forEach((recommendation) => {
    lines.push(`- ${recommendation}`);
  });

  return `${lines.join("\n")}\n`;
}

export function renderAgentsRules(result: AnalysisResult): string {
  const lines = [
    "# Agent Rules Generated From Failed Runs",
    "",
    "<!-- Generated by trace-to-skill. Review before committing. -->",
    "",
    "## Verification",
    ""
  ];

  result.recommendations.forEach((recommendation) => {
    lines.push(`- ${recommendation}`);
  });

  return `${lines.join("\n")}\n`;
}

export function renderSkill(result: AnalysisResult): string {
  const slugs = Array.from(new Set(result.findings.map((finding) => finding.suggestedSkill ?? finding.kind)));
  const name = slugs[0] ?? "agent-verification";

  const lines = [
    "---",
    `name: ${name}`,
    "description: Use when an AI coding agent is about to finish a task or repeat a workflow that previously failed.",
    "---",
    "",
    "# Skill Generated From Agent Traces",
    "",
    "Before completing the task, apply these rules:",
    ""
  ];

  result.recommendations.forEach((recommendation) => {
    lines.push(`- ${recommendation}`);
  });

  lines.push("", "## Evidence Required", "", "- List commands run, results, and any remaining blockers.");

  return `${lines.join("\n")}\n`;
}

function renderFinding(finding: Finding, index: number): string {
  const lines = [
    `### ${index}. ${finding.title}`,
    "",
    `Severity: **${finding.severity}**`,
    "",
    finding.why,
    "",
    "Evidence:"
  ];

  finding.evidence.forEach((evidence) => {
    lines.push(`- \`${evidence.file}:${evidence.line}\` ${evidence.excerpt}`);
  });

  lines.push("", "Suggested rule:", "", `> ${finding.suggestedRule}`, "");

  return lines.join("\n");
}
