import type { ComparisonResult } from "./eval.js";
import type { AnalysisResult, Finding } from "./types.js";

export function renderMarkdown(result: AnalysisResult): string {
  const lines: string[] = [
    "# Agent Learning Report",
    "",
    `Score: **${result.score}/100**`,
    "",
    result.summary,
    "",
    `Generated: ${result.generatedAt}`,
    "",
    "## Findings",
    ""
  ];

  if (result.findings.length === 0) {
    lines.push("No findings.");
  } else {
    result.findings.forEach((finding, index) => {
      lines.push(renderFinding(finding, index + 1));
    });
  }

  lines.push("", "## Suggested AGENTS.md Rules", "");
  result.recommendations.forEach((recommendation) => {
    lines.push(`- ${recommendation}`);
  });

  return `${lines.join("\n")}\n`;
}

export function renderAgentsRules(result: AnalysisResult): string {
  const lines = [
    "# Agent Rules Generated From Failed Runs",
    "",
    "<!-- Generated by trace-to-skill. Review before committing. -->",
    "",
    "## Verification",
    ""
  ];

  result.recommendations.forEach((recommendation) => {
    lines.push(`- ${recommendation}`);
  });

  return `${lines.join("\n")}\n`;
}

export function renderSkill(result: AnalysisResult): string {
  const slugs = Array.from(new Set(result.findings.map((finding) => finding.suggestedSkill ?? finding.kind)));
  const name = slugs[0] ?? "agent-verification";

  const lines = [
    "---",
    `name: ${name}`,
    "description: Use when an AI coding agent is about to finish a task or repeat a workflow that previously failed.",
    "---",
    "",
    "# Skill Generated From Agent Traces",
    "",
    "Before completing the task, apply these rules:",
    ""
  ];

  result.recommendations.forEach((recommendation) => {
    lines.push(`- ${recommendation}`);
  });

  lines.push("", "## Evidence Required", "", "- List commands run, results, and any remaining blockers.");

  return `${lines.join("\n")}\n`;
}

export function renderPrComment(result: AnalysisResult): string {
  const topFindings = result.findings.slice(0, 5);
  const status = result.findings.some((finding) => finding.severity === "critical") ? "needs attention" : "reviewable";
  const lines = [
    "<!-- trace-to-skill-report -->",
    "## trace-to-skill Agent Learning Report",
    "",
    `Score: **${result.score}/100** (${status})`,
    "",
    result.summary,
    ""
  ];

  if (topFindings.length > 0) {
    lines.push("### Top Findings", "");
    topFindings.forEach((finding) => {
      const firstEvidence = finding.evidence[0];
      const evidence = firstEvidence ? ` Evidence: \`${firstEvidence.file}:${firstEvidence.line}\`.` : "";
      lines.push(`- **${finding.severity}**: ${finding.title}.${evidence}`);
    });
    lines.push("");
  }

  if (result.recommendations.length > 0) {
    lines.push("### Suggested Rules", "");
    result.recommendations.slice(0, 5).forEach((recommendation) => {
      lines.push(`- ${recommendation}`);
    });
    lines.push("");
  }

  lines.push("_Generated by trace-to-skill. Review generated rules before committing them._");

  return `${lines.join("\n")}\n`;
}

export function renderComparison(result: ComparisonResult): string {
  return `${[
    "# Agent Improvement Comparison",
    "",
    `Decision: **${result.decision}**`,
    "",
    `Before score: **${result.beforeScore}/100**`,
    `After score: **${result.afterScore}/100**`,
    `Delta: **${result.delta >= 0 ? "+" : ""}${result.delta}**`,
    `Critical findings: **${result.beforeCriticalFindings} -> ${result.afterCriticalFindings}**`,
    "",
    result.message
  ].join("\n")}\n`;
}

function renderFinding(finding: Finding, index: number): string {
  const lines = [
    `### ${index}. ${finding.title}`,
    "",
    `Severity: **${finding.severity}**`,
    "",
    finding.why,
    "",
    "Evidence:"
  ];

  finding.evidence.forEach((evidence) => {
    lines.push(`- \`${evidence.file}:${evidence.line}\` ${evidence.excerpt}`);
  });

  lines.push("", "Suggested rule:", "", `> ${finding.suggestedRule}`, "");

  return lines.join("\n");
}
