import type { ComparisonResult } from "./eval.js";
import type { DoctorResult } from "./doctor.js";
import type { AnalysisResult, Finding, Severity } from "./types.js";

export function renderMarkdown(result: AnalysisResult): string {
  const lines: string[] = [
    "# Agent Learning Report",
    "",
    `Score: **${result.score}/100**`,
    "",
    result.summary,
    "",
    `Generated: ${result.generatedAt}`,
    "",
    "## Findings",
    ""
  ];

  if (result.findings.length === 0) {
    lines.push("No findings.");
  } else {
    result.findings.forEach((finding, index) => {
      lines.push(renderFinding(finding, index + 1));
    });
  }

  lines.push("", "## Suggested AGENTS.md Rules", "");
  result.recommendations.forEach((recommendation) => {
    lines.push(`- ${recommendation}`);
  });

  return `${lines.join("\n")}\n`;
}

export function renderAgentsRules(result: AnalysisResult): string {
  const lines = [
    "# Agent Rules Generated From Failed Runs",
    "",
    "<!-- Generated by trace-to-skill. Review before committing. -->",
    "",
    "## Verification",
    ""
  ];

  result.recommendations.forEach((recommendation) => {
    lines.push(`- ${recommendation}`);
  });

  return `${lines.join("\n")}\n`;
}

export function renderSkill(result: AnalysisResult): string {
  const slugs = Array.from(new Set(result.findings.map((finding) => finding.suggestedSkill ?? finding.kind)));
  const name = slugs[0] ?? "agent-verification";

  const lines = [
    "---",
    `name: ${name}`,
    "description: Use when an AI coding agent is about to finish a task or repeat a workflow that previously failed.",
    "---",
    "",
    "# Skill Generated From Agent Traces",
    "",
    "Before completing the task, apply these rules:",
    ""
  ];

  result.recommendations.forEach((recommendation) => {
    lines.push(`- ${recommendation}`);
  });

  lines.push("", "## Evidence Required", "", "- List commands run, results, and any remaining blockers.");

  return `${lines.join("\n")}\n`;
}

export function renderPrComment(result: AnalysisResult): string {
  const topFindings = result.findings.slice(0, 5);
  const status = result.findings.some((finding) => finding.severity === "critical") ? "needs attention" : "reviewable";
  const lines = [
    "<!-- trace-to-skill-report -->",
    "## trace-to-skill Agent Learning Report",
    "",
    `Score: **${result.score}/100** (${status})`,
    "",
    result.summary,
    ""
  ];

  if (topFindings.length > 0) {
    lines.push("### Top Findings", "");
    topFindings.forEach((finding) => {
      const firstEvidence = finding.evidence[0];
      const evidence = firstEvidence ? ` Evidence: \`${firstEvidence.file}:${firstEvidence.line}\`.` : "";
      lines.push(`- **${finding.severity}**: ${finding.title}.${evidence}`);
    });
    lines.push("");
  }

  if (result.recommendations.length > 0) {
    lines.push("### Suggested Rules", "");
    result.recommendations.slice(0, 5).forEach((recommendation) => {
      lines.push(`- ${recommendation}`);
    });
    lines.push("");
  }

  lines.push("_Generated by trace-to-skill. Review generated rules before committing them._");

  return `${lines.join("\n")}\n`;
}

export function renderCodexIssueReport(result: AnalysisResult): string {
  const relevantFindings = result.findings.filter(isCodexIssueFinding);
  const topFindings = (relevantFindings.length > 0 ? relevantFindings : result.findings).slice(0, 4);
  const primary = topFindings[0];
  const status = primary ? `${primary.title} (${primary.kind}, ${primary.severity})` : "No Codex-specific failure class detected";
  const issueSummary = primary ?
    `trace-to-skill detected ${primary.title} (${primary.kind}). ${primary.why}` :
    result.summary;
  const lines = [
    "# OpenAI Codex Issue Triage Report",
    "",
    `Score: **${result.score}/100**`,
    "",
    `Likely failure class: **${status}**`,
    "",
    result.summary,
    "",
    "## Copy-Paste Issue Body",
    "",
    "```md",
    "### What happened?",
    "",
    issueSummary,
    "",
    "### Detected failure class",
    "",
    primary ? `- ${primary.kind}: ${primary.title} (${primary.severity})` : "- None detected",
    "",
    "### Evidence",
    ""
  ];

  if (topFindings.length === 0) {
    lines.push("- No findings detected.");
  } else {
    topFindings.forEach((finding) => {
      lines.push(`#### ${finding.title}`);
      finding.evidence.slice(0, 6).forEach((evidence) => {
        lines.push(`- ${evidence.file}:${evidence.line} - ${evidence.excerpt}`);
      });
      lines.push("");
    });
  }

  lines.push(
    "### Diagnostics to attach",
    "",
    ...buildDiagnosticChecklist(topFindings),
    "",
    "### Privacy",
    "",
    "- I redacted tokens, API keys, private paths, customer data, and hidden Unicode controls before sharing this trace.",
    "```",
    "",
    "## Findings",
    ""
  );

  if (topFindings.length === 0) {
    lines.push("No findings detected.");
  } else {
    topFindings.forEach((finding, index) => {
      lines.push(renderFinding(finding, index + 1));
    });
  }

  lines.push(
    "",
    "## Reporter Notes",
    "",
    "- Run `trace-to-skill redact <trace> --output redacted-runs` before attaching logs publicly.",
    "- Prefer the shortest trace that reproduces the failure.",
    "- Include exact Codex app/CLI version, OS, model, subscription/workspace, and the command or UI action that failed.",
    "- Link related OpenAI/Codex issues when you know them, but keep the evidence self-contained."
  );

  return `${lines.join("\n")}\n`;
}

export function renderComparison(result: ComparisonResult): string {
  return `${[
    "# Agent Improvement Comparison",
    "",
    `Decision: **${result.decision}**`,
    "",
    `Before score: **${result.beforeScore}/100**`,
    `After score: **${result.afterScore}/100**`,
    `Delta: **${result.delta >= 0 ? "+" : ""}${result.delta}**`,
    `Critical findings: **${result.beforeCriticalFindings} -> ${result.afterCriticalFindings}**`,
    "",
    result.message
  ].join("\n")}\n`;
}

function isCodexIssueFinding(finding: Finding): boolean {
  return finding.kind.startsWith("codex_") ||
    finding.kind === "context_compaction" ||
    finding.kind === "sandbox_permission" ||
    finding.kind === "quota_mismatch" ||
    finding.kind === "codex_resource_leak" ||
    finding.kind === "sensitive_file_access" ||
    finding.kind === "mcp_risk";
}

function buildDiagnosticChecklist(findings: Finding[]): string[] {
  const checklist = new Set<string>();

  findings.forEach((finding) => {
    checklist.add(`- ${finding.suggestedRule}`);
  });

  if (checklist.size === 0) {
    checklist.add("- Attach the exact command, UI action, error text, app/CLI version, OS, and whether the issue reproduces in a clean workspace.");
  }

  return Array.from(checklist).slice(0, 6);
}

export function renderDoctorMarkdown(result: DoctorResult): string {
  const lines = [
    "# Codex Readiness Doctor",
    "",
    `Score: **${result.score}/100**`,
    "",
    result.summary,
    "",
    `Repository: \`${result.root}\``,
    `Generated: ${result.generatedAt}`,
    "",
    "## Checks",
    ""
  ];

  result.checks.forEach((check) => {
    const marker = check.status === "pass" ? "PASS" : check.status === "warn" ? "WARN" : "FAIL";
    lines.push(`- **${marker}** ${check.title}: ${check.detail}`);
    if (check.recommendation) {
      lines.push(`  Recommendation: ${check.recommendation}`);
    }
  });

  lines.push("", "## Agent Risk Findings", "");
  if (result.findings.length === 0) {
    lines.push("No instruction or MCP risk findings detected.");
  } else {
    result.findings.forEach((finding) => {
      const firstEvidence = finding.evidence[0];
      const evidence = firstEvidence ? ` Evidence: \`${firstEvidence.file}:${firstEvidence.line}\`.` : "";
      lines.push(`- **${finding.severity}** ${finding.title}.${evidence}`);
    });
  }

  return `${lines.join("\n")}\n`;
}

export function renderDoctorPrComment(result: DoctorResult, threshold?: number): string {
  const failedChecks = result.checks.filter((check) => check.status === "fail");
  const warningChecks = result.checks.filter((check) => check.status === "warn");
  const criticalFindings = result.findings.filter((finding) => finding.severity === "critical");
  const passesThreshold = threshold === undefined || result.score >= threshold;
  const status = failedChecks.length > 0 || criticalFindings.length > 0 || !passesThreshold ? "needs attention" : "ready";
  const lines = [
    "<!-- trace-to-skill-doctor-report -->",
    "## trace-to-skill Codex Readiness Doctor",
    "",
    `Score: **${result.score}/100**${threshold === undefined ? "" : ` (threshold ${threshold})`} - **${status}**`,
    "",
    result.summary,
    ""
  ];

  const notableChecks = [...failedChecks, ...warningChecks].slice(0, 6);
  if (notableChecks.length > 0) {
    lines.push("### Checks To Review", "");
    notableChecks.forEach((check) => {
      const marker = check.status.toUpperCase();
      lines.push(`- **${marker}** ${check.title}: ${check.detail}`);
      if (check.recommendation) {
        lines.push(`  Recommendation: ${check.recommendation}`);
      }
    });
    lines.push("");
  } else {
    lines.push("### Checks", "", "All readiness checks passed.", "");
  }

  if (result.findings.length > 0) {
    lines.push("### Agent Risk Findings", "");
    result.findings.slice(0, 5).forEach((finding) => {
      const firstEvidence = finding.evidence[0];
      const evidence = firstEvidence ? ` Evidence: \`${firstEvidence.file}:${firstEvidence.line}\`.` : "";
      lines.push(`- **${finding.severity}** ${finding.title}.${evidence}`);
    });
    lines.push("");
  }

  lines.push("_Generated by trace-to-skill. Keep this deterministic report separate from any LLM-written summary._");

  return `${lines.join("\n")}\n`;
}

export function renderSarif(result: AnalysisResult): string {
  const sarif = {
    version: "2.1.0",
    $schema: "https://json.schemastore.org/sarif-2.1.0.json",
    runs: [
      {
        tool: {
          driver: {
            name: "trace-to-skill",
            informationUri: "https://github.com/grnbtqdbyx-create/trace-to-skill",
            rules: buildSarifRules(result.findings)
          }
        },
        results: result.findings.flatMap((finding) => finding.evidence.map((evidence) => ({
          ruleId: finding.kind,
          level: severityToSarifLevel(finding.severity),
          message: {
            text: `${finding.title}: ${evidence.excerpt}`
          },
          locations: [
            {
              physicalLocation: {
                artifactLocation: {
                  uri: evidence.file
                },
                region: {
                  startLine: Math.max(1, evidence.line)
                }
              }
            }
          ],
          properties: {
            severity: finding.severity,
            suggestedRule: finding.suggestedRule
          }
        })))
      }
    ]
  };

  return `${JSON.stringify(sarif, null, 2)}\n`;
}

function renderFinding(finding: Finding, index: number): string {
  const lines = [
    `### ${index}. ${finding.title}`,
    "",
    `Severity: **${finding.severity}**`,
    "",
    finding.why,
    "",
    "Evidence:"
  ];

  finding.evidence.forEach((evidence) => {
    lines.push(`- \`${evidence.file}:${evidence.line}\` ${evidence.excerpt}`);
  });

  lines.push("", "Suggested rule:", "", `> ${finding.suggestedRule}`, "");

  return lines.join("\n");
}

function buildSarifRules(findings: Finding[]): Array<Record<string, unknown>> {
  const byKind = new Map<string, Finding>();
  findings.forEach((finding) => {
    if (!byKind.has(finding.kind)) {
      byKind.set(finding.kind, finding);
    }
  });

  return Array.from(byKind.values()).map((finding) => ({
    id: finding.kind,
    name: finding.title,
    shortDescription: {
      text: finding.title
    },
    fullDescription: {
      text: finding.why
    },
    help: {
      text: finding.suggestedRule
    },
    properties: {
      severity: finding.severity
    }
  }));
}

function severityToSarifLevel(severity: Severity): "none" | "note" | "warning" | "error" {
  if (severity === "critical" || severity === "high") {
    return "error";
  }

  if (severity === "medium") {
    return "warning";
  }

  return "note";
}
